name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:       # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: ragnarStark79
          theme: green

      - name: Commit & Push
        run: |
          git config --global user.name "ragnarStark79"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "update 3d graph" || echo "no changes"
          git push
